#include "alpha_vm_src/headers/avm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void print_usage(char *program_name);
void print_version(void);

int main(int argc, char *argv[]) {
    char *filename = NULL;
    int debug_mode = 0;
    int i;
    
    for(i = 1; i < argc; i++) {
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            print_usage(argv[0]);
            return 0;
        }
        else if(strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--version") == 0) {
            print_version();
            return 0;
        }
        else if(strcmp(argv[i], "-d") == 0 || strcmp(argv[i], "--debug") == 0) {
            debug_mode = 1;
        }
        else if(argv[i][0] != '-') {
            if(filename != NULL) {
                fprintf(stderr, "Error: Multiple input files specified\n");
                print_usage(argv[0]);
                return 1;
            }
            filename = argv[i];
        }
        else {
            fprintf(stderr, "Error: Unknown option '%s'\n", argv[i]);
            print_usage(argv[0]);
            return 1;
        }
    }
    
    if(filename == NULL) {
        fprintf(stderr, "Error: No input file specified\n");
        print_usage(argv[0]);
        return 1;
    }
    
    char *ext = strrchr(filename, '.');
    if(!ext || strcmp(ext, ".abc") != 0) {
        fprintf(stderr, "Warning: Input file '%s' does not have .abc extension\n", filename);
    }
    
    FILE *test_file = fopen(filename, "rb");
    if(!test_file) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", filename);
        perror("fopen");
        return 1;
    }
    fclose(test_file);
    
    if(debug_mode) {
        printf("Alpha Virtual Machine starting...\n");
        printf("Input file: %s\n", filename);
        printf("Debug mode: enabled\n");
        printf("Initializing VM...\n");
    }
    
    avm_initialize();
    
    if(debug_mode) {
        printf("VM initialized successfully\n");
        printf("Loading and executing program...\n");
        printf("========================================\n");
    }
    
    avm_run(filename);
    
    if(debug_mode) {
        printf("========================================\n");
        printf("Program execution completed\n");
        printf("Cleaning up VM resources...\n");
    }
    
    avm_cleanup();
    
    if(debug_mode) {
        printf("VM cleanup completed\n");
        printf("AVM exiting normally\n");
    }
    
    return 0;
}

void print_version(void) {
    printf("Alpha Virtual Machine (AVM) v1.0\n");
    printf("Part of the Alpha Language Implementation\n");
    printf("Built with support for dynamic tables and garbage collection\n");
}

void print_usage(char *program_name) {
    printf("Alpha Virtual Machine (AVM)\n");
    printf("Usage: %s [options] <binary_file.abc>\n", program_name);
    printf("\nOptions:\n");
    printf("  -h, --help     Show this help message\n");
    printf("  -v, --version  Show version information\n");
    printf("  -d, --debug    Enable debug output\n");
    printf("\nExample:\n");
    printf("  %s program.abc\n", program_name);
    printf("\nThe binary file must have been generated by the Alpha compiler.\n");
}